const Links24 = [
  {
    href: '/2024/showpassword',
    num: '1',
    title: 'Show Password',
    image: '/2024Challenge01.jpg',
  },
  {
    href: '/2024/searchfavoritemovie',
    num: '2',
    title: 'Search Favorite Movie',
    image: '/2024Challenge02.jpg',
  },
  {
    href: '/2024/resizabletextarea',
    num: '3',
    title: 'Resizable Text Area',
    image: '/2024Challenge03.jpg',
  },
  {
    href: '/2024/resizablepanels',
    num: '4',
    title: 'Resizable Panels',
    image: '/2024Challenge04.jpg',
  },
  {
    href: '/2024/charactercounter',
    num: '5',
    title: 'Character counter',
    image: '/2024Challenge05.jpg',
  },
  {
    href: '/2024/copytoclipboard',
    num: '6',
    title: 'Copy to clipboard',
    image: '/2024Challenge06.jpg',
  },
  {
    href: '/2024/slugifyinputtext',
    num: '7',
    title: 'Slugify input text',
    image: '/2024Challenge07.jpg',
  },
  {
    href: '/2024/taginputeditor',
    num: '8',
    title: 'Tag input editor',
    image: '/2024Challenge08.jpg',
  },
  {
    href: '/2024/persistformdata',
    num: '9',
    title: 'Presist Form Data',
    image: '/2024Challenge09.jpg',
  },
  {
    href: '/2024/floatingactionbutton',
    num: '10',
    title: 'Floating Action Button',
    image: '/2024Challenge10.jpg',
  },
  {
    href: '/2024/digitalclock',
    num: '11',
    title: 'Digital Clock',
    image: '/2024Challenge11.jpg',
  },
  {
    href: '/2024/quotegenerator',
    num: '12',
    title: 'Quote Generator',
    image: '/2024Challenge12.jpg',
  },
  {
    href: '/2024/temperatureconverter',
    num: '13',
    title: 'Temperature Converter',
    image: '/2024Challenge13.jpg',
  },
  {
    href: '/2024/conditionalselectmenu',
    num: '14',
    title: 'Conditional Select Menu',
    image: '/2024Challenge14.jpg',
  },
  {
    href: '/2024/youtubeembedresponsive',
    num: '15',
    title: 'YouTube Embed Responsive',
    image: '/2024Challenge15.jpg',
  },
  {
    href: '/2024/cssgridgenerator',
    num: '16',
    title: 'CSS Grid Generator',
    image: '/2024Challenge16.jpg',
  },
  {
    href: '/2024/sidenavigation',
    num: '17',
    title: 'Side Navigation',
    image: '/2024Challenge17.jpg',
  },
  {
    href: '/2024/pricingcharttoggle',
    num: '18',
    title: 'Pricing Chart Toggle',
    image: '/2024Challenge18.jpg',
  },
  {
    href: '/2024/multistepform',
    num: '19',
    title: 'Multi Step Form',
    image: '/2024Challenge19.jpg',
  },
  {
    href: '/2024/infinitescroll',
    num: '20',
    title: 'Infinitie Scroll',
    image: '/2024Challenge20.jpg',
  },
  {
    href: '/2024/datepicker',
    num: '21',
    title: 'Date Picker ',
    image: '/2024Challenge21.jpg',
  },
  {
    href: '/2024/kanbanboard',
    num: '22',
    title: 'Kanban Board ',
    image: '/2024Challenge22.jpg',
  },
  {
    href: '/2024/basicexpensetracker',
    num: '23',
    title: 'Basic Expense Tracker',
    image: '/2024Challenge23.jpg',
  },
  {
    href: '/2024/cssboxshadowgenerator',
    num: '24',
    title: 'CSS Box Shadow Generator',
    image: '/2024Challenge24.jpg',
  },
];

export default Links24;
