const Links21 = [
  {
    href: '/2021/challenge1',
    num: '1',
    title: 'Countdown',
    image: '/Challenge1.jpg',
  },
  {
    href: '/2021/challenge2',
    num: '2',
    title: 'ToGoMenu',
    image: '/Challenge2.jpg',
  },
  {
    href: '/2021/challenge3',
    num: '3',
    title: 'Piano',
    image: '/Challenge3.jpg',
  },
  {
    href: '/2021/challenge4',
    num: '4',
    title: 'Keyboaard',
    image: '/Challenge4.jpg',
  },
  {
    href: '/2021/challenge5',
    num: '5',
    title: 'MultipleCheckboxes',
    image: '/Challenge5.jpg',
  },
  {
    href: '/2021/challenge6',
    num: '6',
    title: 'RangeSlider',
    image: '/Challenge6.jpg',
  },
  {
    href: '/2021/challenge7',
    num: '7',
    title: 'TipCalculator',
    image: '/Challenge7.jpg',
  },
  {
    href: '/2021/challenge8',
    num: '8',
    title: 'WeatherForecast',
    image: '/Challenge8.jpg',
  },
  {
    href: '/2021/challenge9',
    num: '9',
    title: 'Carousel',
    image: '/Challenge9.jpg',
  },
  {
    href: '/2021/challenge10',
    num: '10',
    title: 'Verifier',
    image: '/Challenge10.jpg',
  },
  {
    href: '/2021/challenge11',
    num: '11',
    title: 'Expanding and Collapsing',
    image: '/Challenge11.jpg',
  },
  {
    href: '/2021/challenge12',
    num: '12',
    title: 'Rock, Paper, Scissors game',
    image: '/Challenge12.jpg',
  },
  {
    href: '/2021/challenge13',
    num: '13',
    title: 'CustomModal',
    image: '/Challenge13.jpg',
  },
  {
    href: '/2021/challenge14',
    num: '14',
    title: 'Calendar Picker',
    image: '/Challenge14.jpg',
  },
  {
    href: '/2021/challenge15',
    num: '15',
    title: 'Youtube Api',
    image: '/Challenge15.jpg',
  },
  {
    href: '/2021/challenge16',
    num: '16',
    title: 'Rated Stars',
    image: '/Challenge16.jpg',
  },
  {
    href: '/2021/challenge17',
    num: '17',
    title: 'Table Of Content',
    image: '/Challenge17.jpg',
  },
  {
    href: '/2021/challenge18',
    num: '18',
    title: 'Password Generator',
    image: '/Challenge18.jpg',
  },
  {
    href: '/2021/challenge19',
    num: '19',
    title: 'Form Validation',
    image: '/Challenge19.jpg',
  },
  {
    href: '/2021/challenge20',
    num: '20',
    title: 'Tabbed Content',
    image: '/Challenge20.jpg',
  },
  {
    href: '/2021/challenge21',
    num: '21',
    title: 'Simplified Budget',
    image: '/Challenge21.jpg',
  },
  {
    href: '/2021/challenge22',
    num: '22',
    title: 'Credit Card Form',
    image: '/Challenge22.jpg',
  },
  {
    href: '/2021/challenge23',
    num: '23',
    title: 'Toaster',
    image: '/Challenge23.jpg',
  },
  {
    href: '/2021/challenge24',
    num: '24',
    title: 'Table24',
    image: '/Challenge24.jpg',
  },
];

export default Links21;
